TLS insecure option adding
future-architect/vuls pull request #1220
Opened 2021-04-20 13:21 UTC by Koodt

# What did you implement:

SMTPInsecure added to SMTPConf struct
```
SMTPInsecure bool `toml:"smtpInsecure,omitempty" json:"-"`
```

InsecureSkipVerify added to tlsConfig in sendMail
```
tlsConfig := &tls.Config {
    ServerName:         emailConf.SMTPAddr,
    InsecureSkipVerify: emailConf.SMTPInsecure,
}
```
Fixes #1219 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Build from scratch and deploy to docker container

# Checklist:

- [ ] Format your source code by `make fmt`

***Is this ready for review?:*** YES

2021-04-21 03:49 UTC, kotakanbe commented
Hi, 

Please share specific details of what situations you need this for.

2021-04-21 09:16 UTC, Koodt commented
Hi,

in some environments we have testing purposes, we need to skip cert verification to have things running.

2021-04-29 22:41 UTC, kotakanbe requested changes

2021-04-29 22:41 UTC, kotakanbe commented on config/smtpconf.go
> +	SMTPInsecure  bool     `toml:"smtpInsecure,omitempty" json:"-"`
I think SMTPInsecure is confusing whether it is plain text or not. 
How about renaming it to `TLSInsecureSkipVerify`?

2024-04-05 04:03 UTC, shino approved these changes
Nice change!

2024-04-05 04:12 UTC, merged